/** One-sentence explanations for league storyline stats. */
export const statHints = {
  biggestClimber: "Manager who gained the most league places compared to the previous gameweek.",
  biggestFaller: "Manager who dropped the most league places compared to the previous gameweek.",
  woodenSpoonGw: "Lowest scorer in the league for this gameweek.",
  leagueAverageGw: "Mean net score across all managers this gameweek.",
  seasonBestGw: "Highest gameweek score recorded so far this season.",
  seasonWorstGw: "Lowest gameweek score recorded so far this season.",
  mostGameweekWins: "Manager with the most gameweeks finished top of the league table.",
  mostMonthlyWins: "Manager leading the most calendar months on cumulative points.",
  transferTaxSeason: "Most points lost to transfer hits across the season.",
  benchRegretSeason: "Most combined bench points left unused across the season.",
  captainPointsLeader: "Most total points earned from captain picks this season.",
  bestFplRank: "Best overall worldwide FPL rank achieved at any point this season.",
  bestBenchBoost: "Highest net score on the week Bench Boost was played.",
  bestFreeHit: "Highest net score on the week Free Hit was played.",
  bestTripleCaptain: "Highest net score on the week Triple Captain was played.",
  transferHitsLeader: "Most transfer hit points deducted this season.",
  seasonTransferLeader: "Most total transfers made this season.",
  benchPointsLeader: "Most points scored by benched players this season.",
  captaincyLeader: "Best captain return in the selected gameweek.",
  captainCopycat: "Most often picked the same captain as the league majority.",
  captainDifferential: "Most often picked a different captain from the league majority.",
  mostWeeksAtTop: "Most gameweeks spent on top of the league table.",
  mostWeeksLast: "Most gameweeks spent at the bottom of the league table.",
  seasonWoodenSpoonCount: "Most gameweeks with the lowest score in the league.",
  mostTemplate: "Squad most similar to the league's most-owned players.",
  mostContrarian: "Squad least similar to the league's most-owned players.",
  formLeaders: "Total net points over the last three completed gameweeks.",
  gameweekLeader: "Manager(s) with the highest net score this gameweek.",
  monthlyLeader: "Manager(s) leading on cumulative points for the current calendar month.",
  gwWins: "Head-to-head gameweek wins between the two selected managers.",
  squadOverlap: "Average share of starting XI players both managers had in common.",
  sameCaptain: "Gameweeks where both managers captained the same player.",
  rankComparison: "League table position for each manager after every gameweek.",
} as const;

export const insightGroupHints = {
  movement: "Rank changes and the weekly wooden spoon.",
  scoring: "Gameweek highs, lows, and season scoring records.",
  seasonTotals: "Cumulative season stats across transfers, bench, and captaincy.",
  chips: "Best returns when each FPL chip was played.",
  consistency: "Time spent at the top or bottom of the league.",
  squadStyle: "How closely squads match the league template.",
  transfers: "Transfer activity and points left on the bench.",
  captaincy: "Captain choices compared with the rest of the league.",
} as const;
